name: micro
services:
  # portainer-ce
  portainer-ce:
    image: portainer-ce:2.37.0  # 从指定仓库拉取镜像 2.37.0 支持docker版本  29.1.3
    container_name: portainer-ce
    restart: unless-stopped
    ports:
      - "8090:9000"  # 将容器内部的9000端口映射到宿主机的8090端口
#      - "9443:9443"
    environment:
      - TZ=Asia/Shanghai
#      - PORTAINER_HTTP_DISABLE=true # 强制Portainer仅使用HTTPS（禁用HTTP）
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # 允许Portainer管理Docker
      - portainer-ce_data:/data  # 持久化存储Portainer数据
#      - /opt/portainer/certs:/certs  # 挂载宿主机的HTTPS证书到容器内Portainer默认读取证书的路径
    deploy:
      resources:
        limits:
          cpus: "2"          # 限制为2个CPU核心
          memory: 2G        # 限制内存为2GB
        reservations:
          cpus: "0.5"      # 保证至少 0.5 个 CPU 核心
          memory: "512M"   # 保证至少 512MB 内存
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
    networks:
      - portainer-ce-network  # 使用专用网络
volumes:
  portainer-ce_data:  # 声明命名卷用于数据持久化

networks:
  portainer-ce-network:
    driver: bridge
